version: "3"
services:
  db:
    build: ./postgres
    ports:
      - "5433:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  app:
    build: ./server
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "./server:/go/src/app"
    container_name: app
  web:
    build: nginx/.
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  postgresql_data:
